name: update homepage

on:
  schedule:
    - cron: '1 1 * * *'
  issue_comment:
    types: [created, deleted]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: 'x64'
      - name: run local scripts
        run: |
          pip install -r requirements.txt
          python update_readme.py
      - name: commit files
        run: |
          git config --local user.email "1032897296@qq.com"
          git config --local user.name "Yuxiaoy1(bot)"
          git commit -m "update picture of today on $(date +%Y-%m-%d)" -a
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
